// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFErzUfg9QA7eh_MOFz6lId06mONnEp-g',
    appId: '1:474518514090:web:743aa6d145c2f9f35ce3d3',
    messagingSenderId: '474518514090',
    projectId: 'mero-sathi-ai-v1',
    authDomain: 'mero-sathi-ai-v1.firebaseapp.com',
    storageBucket: 'mero-sathi-ai-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ke3URqtK78dF78Edrpk2QDF8s9CyfX4',
    appId: '1:474518514090:android:ca4da05c4dab7f415ce3d3',
    messagingSenderId: '474518514090',
    projectId: 'mero-sathi-ai-v1',
    storageBucket: 'mero-sathi-ai-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_qySq2yfvvXkOYJ7TU2kupHGeAMyN1Ug',
    appId: '1:474518514090:ios:432b6411192934c65ce3d3',
    messagingSenderId: '474518514090',
    projectId: 'mero-sathi-ai-v1',
    storageBucket: 'mero-sathi-ai-v1.firebasestorage.app',
    iosBundleId: 'com.vaf.meroSathi',
  );

}